# Generated by Django 5.1.6 on 2025-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Drawing', 'Drawing'), ('Sketch', 'Sketch')], default='Uncategorized', max_length=50),
        ),
    ]
