# Generated by Django 5.1.6 on 2025-03-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
