# Generated by Django 5.1.6 on 2025-04-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
