# Generated by Django 5.1.6 on 2025-04-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
