# Generated by Django 5.1.6 on 2025-05-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
