# Generated by Django 5.1.6 on 2025-04-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
