# Generated by Django 5.1.6 on 2025-05-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
