# Generated by Django 5.1.6 on 2025-05-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
